application: sinmetal-pushqueue-sample
version: 1
runtime: go
api_version: go1.8

handlers:
- url: /admin/.*
  login: admin
  script: _go_app
- url: /queue/.*
  login: admin
  script: _go_app
- url: /.*
  script: _go_app
